config/routes.rb
Rails.application.routes.draw do
  root 'gossips#show'
  get 'gossips/new'
  resources :gossips
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

 
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  def new
    @gossip = Gossip.new
  end

  def create
    @gossip = Gossip.create(gossip_params)
    @gossip.save
    redirect_to @gossip
  end

  def gossip
  end

  def show
    @gossip = Gossip.find(params[:id])
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    @gossip.update(gossip_params)

    redirect_to root_path
  end

def destroy
        @gossip = Gossip.find(params[:id])
        @gossip.destroy
        redirect_to gossips_path
    end

def index
		@gossips = Gossip.all
	end

private
 		def gossip_params
    	params.permit(:anonymous_author, :content)
  	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/views/gossips/edit.html.erb
<h1> Editer mon gossip </h1>

<%= form_tag gossips_path(@gossip), method: :post do %>
 
  <p> <%= label_tag 'anonymous_author', "Votre pseudo anonyme :" %> </p>
  <p> <%= text_field_tag 'anonymous_author' %> </p>
  <p> <%= label_tag 'content', "Votre nouveau gossip : " %> </p>
  <p> <%= text_area_tag 'content' %> </p>
<p> <%= submit_tag 'Modifier'%></p>
<% end %>





<p> <%= link_to('Voir tous les gossips', gossips_path) %> </p> 

app/views/gossips/index.html.erb
<h1> Voici tout les Gossips !</h1>



  <% @gossips.each do |gossip| %> 

    <ul>
      <li>Auteur du Gossip : <%= gossip.anonymous_author %></li>
      <li>Le gossip : <%= gossip.content %></li>
      <li><%= link_to "Voir le gossip", gossip_path(gossip) %></li>
      <li><%= link_to "Editer le gossip", edit_gossip_path(gossip) %></li>
      <li> <%= link_to "Supprimer le gossip", gossip_path(gossip),
              method: :delete,
              data: { confirm: 'Etes-vous sûr ?' } %> </li>

    </ul>
  <% end %>


<p> <%= link_to('Tu veux gossip encore?', new_gossip_path ) %> </p> 

app/views/gossips/new.html.erb
<h1>Post un nouveau gossip !</h1>
<h2>Dis nous tout !</h2>



<%= form_tag gossips_path(@gossip) do %>

  <p> <%= label_tag 'anonymous_author', "Votre pseudo anonyme :" %> </p>
  <p> <%= text_field_tag 'anonymous_author' %> </p>
  <p> <%= label_tag 'content', "Votre nouveau gossip : " %> </p>
  <p> <%= text_area_tag 'content' %> </p>
<p> <%= submit_tag 'Envoyer'%></p>
<% end %>

app/views/gossips/show.html.erb
<p>
  <strong>Pseudo de l'auteur annonyme : </strong>
  <%= @gossip.anonymous_author %>
</p>

<p>
  <strong>Contenu du gossip : </strong>
  <%= @gossip.content %>

</p>

<p>
  <%= link_to 'Editer le Ragot', edit_gossip_path %>
</p>

<p>
  <%= link_to 'retour', gossips_path %>>
</p>
<%= link_to 'Clique pour détruire', @gossip, method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>